### PR TITLE
Add push-notification

### PR DESCRIPTION
**Pull request by cxxxr**
for example

```
(set-register-method *server* "method"
   (lambda (params)
     ...
     (push-notification ...)
     ...))

### CODE REVIEW

**Comment by fukamachi** [comment]
Why don't you use `notify` or `send-message` directly?

**Comment by cxxxr** [comment]
There is a need to notify after response.
but using response-message might not be a good way.

**Comment by fukamachi** [comment]
Alright, wait a few days.
I'm actively developing at v0.3 branch which has `notify-async`, a function for what you want to do.

**Comment by cxxxr** [comment]
Thank you.

**Pull request closed without merging**
